version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - docker-login
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export IMAGE_NAME=jaydamon' >> $BASH_ENV
            echo 'export DOCKER_REPOSITORY=repo.treescale.com/jaydamon' >> $BASH_ENV
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: setup semantic-release
          command: |
            npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
            npm install -g semantic-release @semantic-release/{git,changelog,exec} semantic-release-plus @semantic-release-plus/docker

      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME .
            /home/circleci/npm/bin/semantic-release