version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - docker-login
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: 'cimg/node:19.7.0'
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export IMAGE_NAME=jaydamon' >> $BASH_ENV
            echo 'export DOCKER_REPOSITORY=cloud.canister.io:5000/jaymond87' >> $BASH_ENV
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: setup semantic-release
          command: |
            npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
            npm install -g semantic-release @semantic-release/{git,changelog,exec} semantic-release-plus @semantic-release-plus/docker
      - run:
          name: Prepare Release
          command: |
            /home/circleci/npm/bin/semantic-release
      - run:
          name: Build and Push Image
          command: |
            bash docker_build_push.sh $DOCKER_REPOSITORY/$IMAGE_NAME $DOCKER_USERNAME $DOCKER_PASSWORD