version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

workflows:
  aws-sync:
    jobs:
      - deploy-dev:
          context: aws-login
      - deploy-prod:
          requires:
            - deploy-dev
          context: aws-login

jobs:
  deploy-dev:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --delete
          from: ./app
          to: "s3://jaydamon-dev.factotum-software.com"
  deploy-prod:
    docker:
      - image: "cimg/python:3.10"
    steps:
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --delete
          from: "s3://jaydamon-dev.factotum-software.com"
          to: "s3://jaydamon.factotum-software.com"
